version: "3.9"

networks:
  public:
    name: public
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 10.100.100.1/24
  # default:
  #   driver: bridge
  # socket_proxy:
  #   name: socket_proxy
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 10.100.100.2/24

services:
## Network Proxy
  traefik:
    container_name: "traefik"
    image: traefik:2.5.6
    restart: always
    networks:
      public:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      # - target: 8080
      #   published: 8080
      #   protocol: tcp
      #   mode: host
      # - target: 8082
      #   published: 8082
      #   protocol: tcp
      #   mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
      - ${DATA_DIR}/traefik/traefik.log:/traefik.log # for fail2ban - make sure to touch file before starting container
    # environment:
    #   - CF_API_EMAIL_FILE=/run/secrets/cloudflare_email
    #   - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key
    #   - HTPASSWD_FILE=/run/secrets/htpasswd # HTPASSWD_FILE can be whatever as it is not used/called anywhere.
    # secrets:
    #   - cloudflare_email 
    #   - cloudflare_api_key
    #   - htpasswd
    command: # CLI arguments
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - "--providers.docker"
      # Enable Docker Swarm mode
      # - --providers.docker.swarmmode=true
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=public"
      # Automatically set Host rule for services
      # - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.apawp.com`)
      # Create an entrypoint "http" listening on port 80
      - "--entrypoints.http.address=:80"
      # Create an entrypoint "https" listening on port 443
      - "--entrypoints.https.address=:443"
      # Create an entrpoint "metrics" listening on port 8082
      - "--entryPoints.metrics.address=:8082"
      # Allow CloudFlares IP Range to set Forwarded Headers
      - "--entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - "--certificatesresolvers.le.acme.email=jebusv20@gmail.com"
      # # Store the Let's Encrypt certificates in the mounted volume
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      # # Use the TLS Challenge for Let's Encrypt
      # - --certificatesresolvers.le.acme.tlschallenge=true
      # - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
      # Enable the Traefik log, for configurations and errors
      - "--log=true"
      - "--log.level=DEBUG" # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      # Enable the access log, with HTTP requests
      - "--accesslog=true"
      - "--accessLog.filePath=/traefik.log"
      # - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      # - --accessLog.filters.statusCodes=400-599
      # Enable the Dashboard and API
      - "--api=true"
      - "--api.dashboard=true"
      # - "--api.insecure=true"
      - "--metrics=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--ping=true"
      #- --pilot.token=$TRAEFIK_PILOT_TOKEN
    labels:
      # Enable Traefik for this service, to make it available in the public network
      - "traefik.enable=true"
      # Use the traefik-public network (declared above)
      - "traefik.docker.network=public"
      #   It can be re-used by other stacks in other Docker Compose files
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      ## Define Global HTTP Catch-all Router - Redirect all HTTP traffic to HTTPS
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.middlewares=https-redirect
      ## Define the Traefik Dashboards Routes
      - "traefik.http.routers.traefik.rule=Host(`traefik.ahawp.com`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      ## Healthcheck/ping
      - "traefik.http.routers.ping.rule=Host(`traefik.ahawp.com`) && Path(`/ping`)"
      - "traefik.http.routers.ping.entrypoints=https"
      - "traefik.http.routers.ping.tls=true"
      - "traefik.http.routers.ping.service=ping@internal"
      - traefik.http.services.ping.loadbalancer.server.port=8080
      ## Metrics
      - "traefik.http.routers.metrics.rule=Host(`traefik.ahawp.com`) && Path(`/metrics`)"
      - "traefik.http.routers.metrics.entrypoints=https"
      - "traefik.http.routers.metrics.tls=true"
      - "traefik.http.routers.metrics.service=prometheus@internal"
      - traefik.http.services.metrics.loadbalancer.server.port=8082
  
  ############################# DATABASES

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${CONFIG_DIR}/prometheus/:/etc/prometheus/
      - ${DATA_DIR}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.ahawp.com`)"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
      - ${CONFIG_DIR}/grafana/provisioning/:/etc/grafana/provisioning/
    # env_file:
    #   - ${CONFIG_DIR}/grafana/config.monitoring
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=foobar
     - GF_USERS_ALLOW_SIGN_UP=false
     - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - public
    user: "104"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.rule=Host(`grafana.ahawp.com`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"


  ############################# FRONTENDS

  # Organizr - Unified Frontend
  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    networks:
      - public
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA_DIR}/organizr:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - fpm=true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.organizr.entrypoints=https"
      - "traefik.http.routers.organizr.rule=Host(`ahawp.com`) || Host(`organizr.ahawp.com`)"
      ## Middlewares
      # - "traefik.http.routers.organizr.middlewares=organizr-redirect@docker,chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.organizr.tls=true"
      - "traefik.http.routers.organizr.service=organizr"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"

  ############################# DOWNLOADERS

  qbittorrent:
    container_name: "qbittorrent"
    image: "linuxserver/qbittorrent"
    restart: unless-stopped
    networks:
      public:
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ${DATA_DIR}/qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - WEBUI_PORT=8081
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorent.entrypoints=https"
      - "traefik.http.routers.qbittorent.rule=Host(`qbit.ahawp.com`)"
      ## Middlewares
      # - "traefik.http.routers.qbittorent.middlewares=middlewares-rate-limit@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorent.tls=true"
      - "traefik.http.routers.qbittorent.service=qbittorent"
      - "traefik.http.services.qbittorent.loadbalancer.server.port=8081"

  ############################# INDEXERS

  # Jackett - Torrent proxy
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: always
    networks:
      public:
    ports:
      - "9117:9117"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA_DIR}/jackett:/config
      - ${DOWNLOADS_DIR}:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jackett.entrypoints=https"
      - "traefik.http.routers.jackett.rule=Host(`jackett.ahawp.com`)"
      ## Middlewares
      # - "traefik.http.routers.jackett.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.service=jackett"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"


  ############################# PVRS

  # Radarr - Movie management
  radarr:
    image: linuxserver/radarr # latest was causing "Error parsing column 45"
    container_name: radarr
    restart: always
    networks:
      public:
    ports:
      - "7878:7878"
    security_opt:
      - no-new-privileges:true
    volumes:
      # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
      # - ${DOCKERDIR}/radarr/MediaCover:/config/MediaCover
      - ${DATA_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MEDIA_DIR}/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.rule=Host(`radarr.ahawp.com`)"
      - "traefik.http.routers.radarr.priority=99"
      ## HTTP Routers Auth Bypass
      # - "traefik.http.routers.radarr-bypass.entrypoints=https"
      # - "traefik.http.routers.radarr-bypass.rule=Host(`radarr.ahawp.com`) && (Headers(`X-Api-Key`, `$RADARR_API_KEY`) || Query(`apikey`, `$RADARR_API_KEY`))"
      # - "traefik.http.routers.radarr-bypass.priority=100"
      ## Middlewares
      # - "traefik.http.routers.radarr-bypass.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.radarr.middlewares=chain-oauth@file"
      ## HTTP Services
      # - "traefik.http.routers.radarr-bypass.service=radarr"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.service=radarr"

  # Sonarr - TV Shows management
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    networks:
      public:
    ports:
      - "8989:8989"
    security_opt:
      - no-new-privileges:true
    volumes:
      # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
      # - ${DOCKERDIR}/sonarr/MediaCover:/config/MediaCover
      - ${DATA_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MEDIA_DIR}/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.ahawp.com`)"
      - "traefik.http.routers.sonarr.priority=99"
      ## HTTP Routers Auth Bypass
      # - "traefik.http.routers.sonarr-bypass.entrypoints=https"
      # - "traefik.http.routers.sonarr-bypass.rule=Host(`sonarr.ahawp.com`) && (Headers(`X-Api-Key`, `$SONARR_API_KEY`) || Query(`apikey`, `$SONARR_API_KEY`))"
      # - "traefik.http.routers.sonarr-bypass.priority=100"
      ## Middlewares
      # - "traefik.http.routers.sonarr-bypass.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.sonarr.middlewares=chain-oauth@file"
      ## HTTP Services
      # - "traefik.http.routers.sonarr-bypass.service=sonarr"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  ############################# MEDIA

  plexms:
    container_name: plexms
    image: plexinc/pms-docker
    restart: unless-stopped
    networks:
      - public
    ports:
      - "32400:32400"
      # - "3005:3005/tcp"   #USED FOR PLEX COMPANION
      # - "8324:8324/tcp"   #USED FOR ROKU
      # - "32469:32469/tcp" #USED FOR DLNA
      # - "1900:1900/udp"   #USED FOR DLNA
      # - "32410:32410/udp" #USED FOR GSM
      # - "32412:32412/udp" #USED FOR GSM
      # - "32413:32413/udp" #USED FOR GSM
      # - "32414:32414/udp" #USED FOR GSM
    volumes:
      - ${MEDIA_DIR}/movies:/media/movies
      - ${MEDIA_DIR}/tvshows:/media/tvshows
      - ${DATA_DIR}/plexms:/config
      # - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PLEX_GID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_IP=${PLEX_IP}
